import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams, Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { labApi } from '../../services/labApi';
import {
  UploadCloud,
  FileText,
  AlertTriangle,
  CheckCircle2,
  ShieldCheck,
  ShieldAlert,
  ArrowRight,
  Info,
  Calendar,
  FileCheck,
  Cpu,
  Layers,
  Sparkles
} from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../../components/Card/Card';
import { Button } from '../../components/Button/Button';
import { StatusBadge } from '../../components/StatusBadge/StatusBadge';
import './LabReportUpload.css';

export function LabReportUpload() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const initialPatientId = searchParams.get('patientId') || 'PX123456';

  const { currentLab } = useAuth();
  const [patientId, setPatientId] = useState(initialPatientId);
  const [testType, setTestType] = useState('Complete Blood Count (CBC) with Differential');
  const [collectionDate, setCollectionDate] = useState(new Date().toISOString().slice(0, 16));
  const [selectedFile, setSelectedFile] = useState(null);
  const [isDragOver, setIsDragOver] = useState(false);

  const [consentCheck, setConsentCheck] = useState(null);
  const [checkingConsent, setCheckingConsent] = useState(false);

  // Processing pipeline states
  const [isUploading, setIsUploading] = useState(false);
  const [pipelineStep, setPipelineStep] = useState(null);
  const [uploadError, setUploadError] = useState(null);

  // Verify visit consent whenever patientId changes
  useEffect(() => {
    async function checkConsent() {
      if (!patientId || !currentLab) return;
      setCheckingConsent(true);
      try {
        const res = await labApi.getVisitConsent(patientId.trim().toUpperCase(), currentLab.id);
        setConsentCheck(res);
      } catch (err) {
        console.error(err);
      } finally {
        setCheckingConsent(false);
      }
    }
    checkConsent();
  }, [patientId, currentLab]);

  const hasApprovedConsent = consentCheck?.exists && consentCheck?.consent?.status === 'APPROVED';

  const handleFileDrop = (e) => {
    e.preventDefault();
    setIsDragOver(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      if (file.type === 'application/pdf' || file.name.endsWith('.pdf')) {
        setSelectedFile(file);
        setUploadError(null);
      } else {
        setUploadError('Please select a valid Laboratory PDF report file.');
      }
    }
  };

  const handleFileSelect = (e) => {
    if (e.target.files && e.target.files[0]) {
      setSelectedFile(e.target.files[0]);
      setUploadError(null);
    }
  };

  const handleAttachAndProcess = async (e) => {
    e.preventDefault();
    if (!hasApprovedConsent) {
      setUploadError('Upload blocked: Patient visit consent is required before attaching reports.');
      return;
    }

    try {
      setIsUploading(true);
      setUploadError(null);

      // Stage 1: Upload accepted
      const uploadRes = await labApi.uploadReport({
        patientId: patientId.trim().toUpperCase(),
        lab: currentLab,
        testType,
        collectionDate,
        file: selectedFile
      });

      if (!uploadRes.success) {
        setUploadError(uploadRes.error);
        setIsUploading(false);
        return;
      }

      const newReportId = uploadRes.report.report_id;

      // Stage 2: Simulate Clinical Processing Engine (Section 10.4)
      await labApi.processReportThroughEngine(newReportId, (progress) => {
        setPipelineStep(progress);
      });

      // Navigate to Review screen
      navigate(`/lab/reports/${newReportId}/review`);
    } catch (err) {
      setUploadError(err.message || 'Pipeline execution failed.');
      setIsUploading(false);
    }
  };

  return (
    <div className="lab-report-upload-view animate-fade-in">
      <div className="page-header">
        <h1 className="page-title">Attach Laboratory Report PDF</h1>
        <p className="page-subtitle">
          Ingest original laboratory report PDF into platform clinical processing pipeline.
        </p>
      </div>

      {/* State differentiation notice per Section 10.4 */}
      <div className="lifecycle-notice-bar">
        <Info size={16} />
        <span>
          <strong>Handbook Requirement (Section 10.4):</strong> Upload, Clinical Processing, Validation, and Publication are distinct sequential states. Uploading a report does NOT automatically publish it to the patient.
        </span>
      </div>

      <div className="upload-layout-grid">
        <div className="upload-main-form-col">
          <Card>
            <CardHeader>
              <CardTitle>Laboratory Ingestion Specimen Form</CardTitle>
              <CardDescription>
                Attach the original PDF generated by your laboratory information system.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleAttachAndProcess} className="upload-form">
                {/* Patient ID input with live consent check */}
                <div className="form-group">
                  <label className="form-label">
                    Target Patient Platform ID <span className="req">*</span>
                  </label>
                  <div className="input-with-check">
                    <input
                      type="text"
                      className="form-input mono"
                      value={patientId}
                      onChange={(e) => setPatientId(e.target.value.toUpperCase())}
                      placeholder="e.g. PX123456"
                      required
                    />
                    <div className="consent-status-indicator">
                      {checkingConsent ? (
                        <span className="chk-label">Verifying visit consent...</span>
                      ) : hasApprovedConsent ? (
                        <span className="chk-approved">
                          <CheckCircle2 size={16} />
                          Visit Authorized (VIS: {consentCheck.consent.id})
                        </span>
                      ) : (
                        <span className="chk-blocked">
                          <ShieldAlert size={16} />
                          Consent Missing / Required
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Consent Gate Alert if missing */}
                {!hasApprovedConsent && !checkingConsent && (
                  <div className="consent-gate-banner">
                    <AlertTriangle size={18} />
                    <div className="banner-text">
                      <strong>Per-Visit Consent Gate Block:</strong> No approved visit consent exists for patient <strong>{patientId}</strong> at <strong>{currentLab?.name}</strong>.
                      <div className="action-row">
                        <Link to={`/lab/patients/${patientId}/verify`}>
                          <Button variant="secondary" size="sm">
                            Go to Patient Consent Gate (Verify OTP/QR)
                          </Button>
                        </Link>
                      </div>
                    </div>
                  </div>
                )}

                <div className="form-row-2">
                  <div className="form-group">
                    <label className="form-label">
                      Diagnostic Test Panel <span className="req">*</span>
                    </label>
                    <select
                      className="form-input"
                      value={testType}
                      onChange={(e) => setTestType(e.target.value)}
                    >
                      <option value="Complete Blood Count (CBC) with Differential">
                        Complete Blood Count (CBC) with Differential
                      </option>
                      <option value="Comprehensive Metabolic Panel (CMP) & HbA1c">
                        Comprehensive Metabolic Panel (CMP) & HbA1c
                      </option>
                      <option value="Lipid Profile & Atherogenic Ratios">
                        Lipid Profile & Atherogenic Ratios
                      </option>
                      <option value="Renal Function & Electrolyte Battery">
                        Renal Function & Electrolyte Battery
                      </option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">
                      Specimen Draw Date & Time <span className="req">*</span>
                    </label>
                    <input
                      type="datetime-local"
                      className="form-input"
                      value={collectionDate}
                      onChange={(e) => setCollectionDate(e.target.value)}
                      required
                    />
                  </div>
                </div>

                {/* File Dropzone */}
                <div className="form-group">
                  <label className="form-label">
                    Laboratory Source PDF File <span className="req">*</span>
                  </label>
                  <div
                    className={`file-dropzone ${isDragOver ? 'dragover' : ''} ${selectedFile ? 'file-ready' : ''}`}
                    onDragOver={(e) => { e.preventDefault(); setIsDragOver(true); }}
                    onDragLeave={() => setIsDragOver(false)}
                    onDrop={handleFileDrop}
                  >
                    <input
                      type="file"
                      id="pdf-file-input"
                      accept=".pdf,application/pdf"
                      onChange={handleFileSelect}
                      style={{ display: 'none' }}
                    />

                    {selectedFile ? (
                      <div className="file-info-preview">
                        <FileCheck size={36} className="file-ok-icon" />
                        <div>
                          <div className="filename-text">{selectedFile.name}</div>
                          <div className="filesize-text">
                            {(selectedFile.size / 1024).toFixed(1)} KB • Digital/Scanned PDF
                          </div>
                        </div>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => setSelectedFile(null)}
                        >
                          Change
                        </Button>
                      </div>
                    ) : (
                      <label htmlFor="pdf-file-input" className="dropzone-label">
                        <UploadCloud size={40} className="upload-cloud-icon" />
                        <span className="drop-title">
                          Click to browse or drag & drop laboratory PDF report
                        </span>
                        <span className="drop-sub">
                          Accepts digital native PDFs or scanned optical image PDFs (up to 15MB)
                        </span>
                      </label>
                    )}
                  </div>
                </div>

                {uploadError && (
                  <div className="upload-error-box animate-fade-in">
                    <AlertTriangle size={18} />
                    <span>{uploadError}</span>
                  </div>
                )}

                {/* Processing Pipeline Modal Overlay / Status */}
                {isUploading && (
                  <div className="pipeline-progress-box animate-fade-in">
                    <div className="progress-header">
                      <Cpu size={20} className="cpu-pulse" />
                      <strong>Executing Clinical Processing Pipeline (Person 1 Layer 4)</strong>
                    </div>
                    <div className="pipeline-steps-list">
                      <div className={`step-row ${pipelineStep?.step >= 1 ? 'done' : 'active'}`}>
                        <span className="step-badge">1</span>
                        <span>Acquisition & Digital vs Scanned PDF Classification</span>
                      </div>
                      <div className={`step-row ${pipelineStep?.step >= 2 ? 'done' : pipelineStep?.step === 1 ? 'active' : ''}`}>
                        <span className="step-badge">2</span>
                        <span>Direct Text Extraction & OCR Normalization</span>
                      </div>
                      <div className={`step-row ${pipelineStep?.step >= 3 ? 'done' : pipelineStep?.step === 2 ? 'active' : ''}`}>
                        <span className="step-badge">3</span>
                        <span>Laboratory Syntax Parsing (Analyte Names, Units, Values)</span>
                      </div>
                      <div className={`step-row ${pipelineStep?.step >= 4 ? 'done' : pipelineStep?.step === 3 ? 'active' : ''}`}>
                        <span className="step-badge">4</span>
                        <span>Extraction Validation & Reference Range Resolution</span>
                      </div>
                      <div className={`step-row ${pipelineStep?.step >= 5 ? 'done' : pipelineStep?.step === 4 ? 'active' : ''}`}>
                        <span className="step-badge">5</span>
                        <span>Clinical Finding Generation & Multi-biomarker Pattern Detection</span>
                      </div>
                    </div>
                    <div className="pipeline-spinner-footer">
                      <div className="spinner spinner-primary" />
                      <span>{pipelineStep?.name || 'Initiating ingestion pipeline...'}</span>
                    </div>
                  </div>
                )}

                <div className="form-actions-bar">
                  <Button
                    type="submit"
                    variant="primary"
                    size="lg"
                    disabled={!hasApprovedConsent || isUploading}
                    loading={isUploading}
                    icon={<Layers size={18} />}
                  >
                    Attach & Ingest Through Clinical Engine
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>

        {/* Pipeline Info Sidebar */}
        <div className="upload-side-info">
          <Card>
            <CardHeader>
              <CardTitle>Ingestion Contract (Layer 4)</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="side-contract-details">
                <div className="contract-point">
                  <div className="c-dot" />
                  <div>
                    <strong>Dual Ingestion Paths:</strong>
                    <p>Both digital-native and scanned image PDFs normalize to common text stream.</p>
                  </div>
                </div>
                <div className="contract-point">
                  <div className="c-dot" />
                  <div>
                    <strong>Preserved Artifact:</strong>
                    <p>Original laboratory PDF remains immutable and accessible alongside structured observations.</p>
                  </div>
                </div>
                <div className="contract-point">
                  <div className="c-dot" />
                  <div>
                    <strong>Mandatory Lab Review:</strong>
                    <p>Parsed biomarkers and detected patterns require biochemist sign-off before patient publication.</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
